### ISSUE TITLE
settings broken for new users

### ISSUE THREAD

**Issue by soapdog** [soapdog/patchfox#130]
The move to add multiple identities to Patchfox introduces a bug for new users. Since there is no default identity set, the settings package fails to load. This only affects new users. Users who were already set up when the transition into multiples identities occurred are not affected.

This is a blocking bug.

**Comment by soapdog** [comment]
the bug is related to an `undefined` value in `getDefaultIdentity`.

**Comment by soapdog** [comment]
@rmdes this should fix the problem you were seeing.

**Comment by rmdes** [comment]
I'm testing it.. I'm being confronted to very weird behaviors.. Browser hanging, patchfox completely unresponsive having to refresh the entire page to have buttons to react like they are supposed to.. I'm not saying it comes from Patchfox but as long as I stay on my npm ssb server identity, it all works fine.. The moment I switch to another identity it becomes buggy.. :/

**Comment by rmdes** [comment]
Also there is some conflicts when Firefox is tuned to open ssb:// links by default, I click something on Patchfox and Manyverse open.. Alright I think I'm going to :

Let my desktop manyverse ID on its own (isolated)

And configure Firefox to ask me which client I want to use instead of defaulting to Manyverse, maybe that's part of the problem.

**Comment by soapdog** [comment]
It depends on which kind of links you're trying to open. What kind of `ssb://` links are giving you trouble?

Be aware that Patchfox can't connect to Manyverse (I go into more details about that in another issue you commented).
