### ISSUE TITLE
doc: why is FF developer edition required?

### ISSUE THREAD

**Issue by edrex** [soapdog/patchfox#19]
Is there some experimental API used that's only available in DE?

**Comment by soapdog** [comment]
@edrex I am changing a lot of stuff right now but the main thing is that only Dev Edition and Nightly allow installing unsigned add-ons.

**Comment by edrex** [comment]
Thanks, submitted a doc change with that

**Comment by soapdog** [comment]
hey @edrex I've closed that PR #21 but I manually copied your changes into the readme. A lot changed since you sent the PR and I couldn't merge it.

Also you can now [Install Patchfox from Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/addon/patchfox/) if you want the alpha version. This is signed and will run in any Firefox 65+ version.

Thanks for your help and the PR. I'm adding some more fixes and this should go up in a couple days along side the other changes.
