### ISSUE TITLE
installation process fails

### ISSUE THREAD

**Issue by myf** [soapdog/patchfox#6]
i tried to follow the installation process. went to `about:debugging` and clicked `Load Temporary Add-on`. Then I selected the `patchfox.json` in the patchfox folder but was alerted with error 
```
There was an error during installation: Directory /home/myf/...../patchfox/host_app does not contain a valid install manifest
```
please verify if it's the right method

**Comment by myf** [comment]
hmm from looking around in commit history i found out that there used to have a bit more content in this repo before the refactor. I am assuming that the firefox plugin has been move to elsewhere after the refactor?

**Comment by soapdog** [comment]
@myf the add-on was not moved. I reorganized the files because both the `host_app`  and the add-on were mixed into a single folder. I first separated them and now I moved the `host_app` into its own project called [scuttle-shell](https://github.com/soapdog/scuttle-shell). 

I am now double checking fresh installations and will get back.

**Comment by soapdog** [comment]
Closing this because I am rewriting everything. It is a new codebase and whatever was happening shouldn't happen anymore.
