### ISSUE TITLE
Allow account restoration like Maniverse

### ISSUE THREAD

**Issue by Ryuno-Ki** [soapdog/patchfox#64]
Hi @soapdog,

I just verified, that I could use a single identity across multiple devices [although the docs say, this isn't possible: https://www.scuttlebutt.nz/faq/applications/multiple-devices].

I managed to figure that out with the help of @staltz!

[Manyverse](https://f-droid.org/en/packages/se.manyver/) asks you for an account recovery option on initial load.
After digging into the [GitLab repository](https://gitlab.com/staltz/manyverse/issues/264) I've learned about a `toWords` invocation. Searching the repository for it led me to [its implementation](https://gitlab.com/staltz/manyverse/blob/a59fab4e1a95a253ff0707c3db562ea5b6ae8c54/src/backend/plugins/keysUtils.ts#L23).

So if you manage to get [ssb-keys-mnemonic](https://www.npmjs.com/package/ssb-keys-mnemonic) shipped, you can generate a backup for other apps to use!

The code would look around these lines:

```js
const path = require('path')
const fs = require('fs')

const mnemonic = require('ssb-keys-mnemonic')

const secret = path.join(process.env.HOME, '.ssb', 'secret')
fs.readFile(secret, 'utf8', function (error, content) {
  if (error) {
    console.error(error)
    return
  }
  // Somehow strip the comments now. Then
  const keys = JSON.parse(content)
  const words = mnemonic.keysToWords(keys)
  console.log(words)
})
```

**Comment by Ryuno-Ki** [comment]
The [opposite direction](https://gitlab.com/staltz/manyverse/blob/a59fab4e1a95a253ff0707c3db562ea5b6ae8c54/src/backend/restore.ts#L40) would be `keys = Mnemonic.wordsToKeys(wordsArr.join(' '))`, I guess.

**Comment by soapdog** [comment]
@Ryuno-Ki,

## on running the same identity on multiple devices

 it is not safe to run the same identity in multiple devices. The only people running multiple devices are either doing that by running _sbot_ on a VPS and connecting to it from multiple devices, or, doing it with alternate identities which are not their main identity.

Running on multiple devices **will break your feed.** it is almost impossible to do it safe because all messages are signed and include the signature for the previous message in the chain, so if you have the same identity in two machines and they are not up to date with each other (quite common in our protocol) then you will end up posting from one device before it caught up with your other device causing it to use the same sequence number and the same signature of a previous message but a different content. This is what we call **forking a feed** and then peers will start reject peering with your identity. Your messages will stop propagating to peers who have the other identity and you will end up having to create a totally new identity, that previous one will be forked and unrecoverable. This is a big no no.

## On identity recovery

The act of moving an identity to a new device is common, you upgrade your machine for example and need to move your data. That is safe because you're not posting from the old machine anymore, you just wait for the data to sync and there you go.

It is not possible to do that from patchfox because patchfox doesn't have access to the filesystem. We can't write the files needed to restore an identity from a WebExtension.

The good news is that I am working on [a self-contained app to do just that](https://github.com/ssbc/ssb-backup-tool).

## conclusion

So this issue is not really applicable to patchfox because patchfox is just a client, it doesn't contain the server part that handles accounts and running on multiple devices is anti-pattern and dangerous and something that all the core developers really tell you not to do.

**Comment by Ryuno-Ki** [comment]
I wasn't able to open the referenced thread, but could the docs in https://www.scuttlebutt.nz/faq/applications/multiple-devices be made more explicit?

**Comment by soapdog** [comment]
@Ryuno-Ki people are working on a whole new site.

**Comment by Ryuno-Ki** [comment]
Link? Perhaps I could flag that so it get fixed in the next version :-)

**Comment by soapdog** [comment]
@Ryuno-Ki test deploy is at https://scuttlebutt.netlify.com/ but I don't know in which repo it is being worked on. Try checking the SSBC org in github.
