### ISSUE TITLE
patchfox hijacks any search that begins with "ssb" 

### ISSUE THREAD

**Issue by masukomi** [soapdog/patchfox#67]
Let's assume i want to find a list of SSB pubs on the web. I might search for "ssb pubs" in my address bar.

HOWEVER, because the search starts with "ssb" it is hijacked by Patchfox. As I usually do _not_ have a SSB back end running this results in no results.

This makes searching for anything involving scuttlebutt on the web very frustrating. You search, say "damn it" and then rearrange your search terms if you have figured out why this is happening.

I think it should be registering itself as a search engine and show up in the "one-click search engines" pane where users can specify a helpful short keyword if they want.

**Comment by cryptix** [comment]
That’s weird.. I would have assumed the protocol handler only kicks in after `ssb://` and then also if it’s a valid looking thing afterwards..?

**Comment by soapdog** [comment]
@masukomi and @cryptix when the custom URL stopped working because it was not a valid URI, I made a search option as well, by typing `ssb <whatever>` it searches in SSB. 

![image](https://user-images.githubusercontent.com/23247/75337501-05d59700-5885-11ea-9fce-cd36a20d0379.png)

When you search the awesome bar popup shows you what will happen. In the first line there you can see the default action `Search Secure Scuttlebutt` with an add-on default icon (it should have been patchfox icon...), below it you can see a normal magnifying glass with `ssb pubs` which will search using your default search engine. You can use the up and down arrow to move in this list while typing.

I'll see if I can provide a way to disable this search feature in the settings but I don't think it will be possible as this is defined in the manifest. I do think it is a useful feature to be able to search SSB from inside the browser. If `ssb-query` was faster I could even provide search suggestions rsrsrs.

**Comment by soapdog** [comment]
Changed the search keyword to be `ssb?` instead of `ssb`. This has been pushed already.
